name: burla_xatun
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter_bloc: ^9.1.1
  device_preview: ^1.2.0
  table_calendar: ^3.1.3
  flutter_calendar_carousel: ^2.4.4
  equatable: ^2.0.7
  go_router: ^14.6.3
  carousel_slider: ^5.0.0
  syncfusion_flutter_charts: ^28.1.38
  intl_utils: ^2.8.8 
  emoji_picker_flutter: ^4.3.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.19.1
  video_player: ^2.9.5
  chewie: ^1.10.0
  pinput: ^5.0.1
  image_picker: ^1.1.2
  get_it: ^8.0.3
  intl: ^0.19.0
  flutter_html: ^3.0.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  video_thumbnail: ^0.5.6
  intl_mobile_field: ^2.0.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_native_splash: ^2.4.5


flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/icons/
    - assets/png/

flutter_native_splash:
  image: assets/png/Burla_Xatun_splash_screen.png
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  android: true
  ios: true
  android_12:
    image: assets/png/Burla_Xatun_splash_screen.png
    icon_background_color: "#FFFFFF"
    color: "#FFFFFF"
    color_dark: "#FFFFFF"

